### ISSUE TITLE
Create presentation slides

### ISSUE THREAD

**Issue by lgcmotta** [lgcmotta/tdc-vertical-slice-architecture#8]
## TODO

- [ ] Criar template de slides
- [ ] Criar um detalhamento do summary da palestra, pensando no tempo total da palestra (35min)
- [ ] Trazer o código para os slides
   
## Summary
- Apresentação dos palestrantes (Breve introdução sobre nós)
- Introdução ao assunto
   - Contexto (trabalhar em cima do texto de apresentação da palestra)
   - Motivação da palestra (experiência em diversos sistemas utilizando .NET com problemas arquiteturais similares a medida que evoluem)
- Apresentação do problema arquitetural com n-layers
   - Alto acoplamento entre as camadas
   - Classes com mais de uma responsabilidade
   - Dificil manutenabilidade e legibilidade
   - Alta complexibilidade
- Apresentação da solução com vertical slices
   - Conceito
   - Combinação com outras tecnologias de mercado
   - Possível utilização sem as tecnologias de mercado
   - Combinação com outros patterns: CQRS, Event Sourcing, DDD, Transaction Script
   - Prós e Contras
- Tempo reservado para dúvidas
